name: food_scanner_app
description: A sophisticated Food Scanner App with professional UI.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  provider: ^6.0.5
  mobile_scanner: ^6.0.7
  shared_preferences: ^2.5.2
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/login_bg.jpg
    - assets/images/logo.png
    - assets/images/home_bg.jpg

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700

dependency_overrides:
  firebase_auth_platform_interface: ^7.2.0
